config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'
  resources :players
  resources :gamerooms
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  include CableReady::Broadcaster
  before_validation(on: :create) do
    self.state = [
      [nil,nil, nil, nil, nil,nil,nil,nil,nil] ,
        [nil,nil, nil, nil, nil,nil,nil,nil,nil] ,
        [nil,nil, nil, nil, nil,nil,nil,nil,nil] ,
        [nil,nil, nil, nil, nil,nil,nil,nil,nil] ,
        [nil,nil, nil, nil, nil,nil,nil,nil,nil] ,
       [nil,nil, nil, nil, nil,nil,nil,nil,nil] ,
        [nil,nil, nil, nil, nil,nil,nil,nil,nil] ,
        [nil,nil, nil, nil, nil,nil,nil,nil,nil] ,
       [nil,nil, nil, nil, nil,nil,nil,nil,nil] 
    ]
      self.cell_active = {
        "unit_1": true,
         "unit_2": true,
         "unit_3": true,
         "unit_4": true,
         "unit_5": true,
         "unit_6": true,
         "unit_7": true,
         "unit_8": true,
         "unit_9": true,
      }

      {
        "1": {
            active: true,
            finished: false
        },
        "2": {
            active: true,
            finished: false
        },
        "3": {
            active: true,
            finished: false
        },
       "4": {
            active: true,
            finished: false
        },
        "5": {
            active: true,
            finished: false
        },
        "6": {
            active: true,
            finished: false
        },
        "7": {
            active: true,
            finished: false
        },
        "8": {
            active: true,
            finished: false
        },
        "9": {
            active: true,
            finished: false
        }
    } 
    
  end
  belongs_to :gameroom
  WINNING_COMBOS = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    [0, 4, 8],
    [2, 4, 6]
  ].freeze

  GAME_START = {
    "unit_1": true,
     "unit_2": true,
     "unit_3": true,
     "unit_4": true,
     "unit_5": true,
     "unit_6": true,
     "unit_7": true,
     "unit_8": true,
     "unit_9": true,
  }

  def move(game,cell)
    self.turn == true ? (self.state[game-1][cell-1] = "x") : (self.state[game-1][cell-1] = "o")
    self.toggle!(:turn)
    puts "test 1"
    if self.cell_active == GAME_START.stringify_keys 
      puts "test 2"
      (1..9).each do |v| 
        cell_active["unit_#{v}"] = false
        puts cell_active["unit_#{v}"]
      end
      cell_active["unit_#{cell}"] = !cell_active["unit_#{cell}"]
      puts "test 3"
    else 
      cell_active["unit_#{cell}"] = !cell_active["unit_#{cell}"]
      cell_active["unit_#{game}"] = !cell_active["unit_#{game}"]
    end
      self.save!
      #  active(cell)
    
  end
  
  def active(cell)
    cable_ready[RoomChannel].morph(
      selector: "##{cell}",
      html: render(UnitComponent.new(game_id: cell, board: self))
    ).broadcast_to(Gameroom.find(self.gameroom.id))
  end

  def check_unit(unit)
    WINNING_COMBOS.any? do |x|
      x.all? do |y|
        state[unit-1][y] == 'x'
      end
    end

  end
  
end

app/models/gameroom.rb
class Gameroom < ApplicationRecord
  belongs_to :player
  has_many :messages, dependent: :destroy
  has_one :board, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  include CableReady::Broadcaster
  belongs_to :player
  belongs_to :gameroom

  # after_save :send

  # def send
  #   cable_ready[ChatChannel].console_log("test test")

  # end
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include CableReady::Broadcaster
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  # after_create do
  #   cable_ready["visitors"] # send to everyone subscribed to the channel streaming from "visitors"
  #     .console_log(message: "Welcome #{self.name} to the site!") # all users will see a message appear in their browser's Console Inspector
  #     .broadcast # send all queued operations to all ExampleChannel subscribers
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CableReady::Broadcaster 
   helper_method :current_player

end

app/controllers/gamerooms_controller.rb
class GameroomsController < ApplicationController
  # before_action :set_player
  def index
    @gamerooms = Gameroom.all
  end

  def show
    @gameroom = Gameroom.find(params[:id])
    @player
  end

  def new
    @gameroom = Gameroom.new
    @player
  end

  def create
    @gameroom = Gameroom.new(gameroom_params)

    if @gameroom.save
      @gameroom.board = Board.create(gameroom_id: @gameroom.id)
      redirect_to gameroom_path(@gameroom)
    end
  end

  private

  def set_player
    @player = current_player
  end

  def gameroom_params
    params.require(:gameroom).permit(:player_id, :room_name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new; end

  def create; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def instructions; end

  def about; end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player
  def show
    @player = Player.find(params[:id])
  end

  def edit; end

  private

  def set_player
    @player = current_player
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gamerooms_helper.rb
module GameroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/gamerooms/index.html.erb
<p> Game Rooms</p>
<div class=" w-screen grid grid-cols-3 ">
 <% @gamerooms.each do |gameroom| %>
 
 <div class= " bg-gray-200 col-span-1  ">
   <p>
     <%= gameroom.player.email %>
  </p>
  <p>
     <%= link_to "Join game room", gameroom_path(gameroom) %> 
     
  </p>
</div>

<% end %>
</div>

app/views/gamerooms/new.html.erb
<%= form_for @gameroom do |f| %>
  <%= f.label "Game Room Name" %>
  <%= f.text_field :room_name, value: "#{current_player.email}'s room" %>
   
   
  <%= f.hidden_field :player_id, value: current_player.id %>
  <%= f.submit "Submit", disable_with: "Submiting..." %>
<% end %>

app/views/gamerooms/show.html.erb
<% current_player %>
<div data-controller= "room" id= "<%= dom_id(@gameroom) %>" class=" w-full h-full flex  justify-center items-center" data-room-id-value = <%= @gameroom.id %>>
<%= render(BoardComponent.new(board: @gameroom.board)) %>

    
</div>


<div  data-controller="chat" data-chat-id-value ="<%= @gameroom.id %>" id= "<%= dom_id(@gameroom) %>">

<%= render(ChatboxComponent.new(gameroom: @gameroom, player: current_player)) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UltimateTicTac</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
   
   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <%= action_cable_meta_tag %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
   
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Messages#create</h1>
  <p>Find me in app/views/messages/create.html.erb</p>
</div>

app/views/messages/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Messages#new</h1>
  <p>Find me in app/views/messages/new.html.erb</p>
</div>

app/views/pages/home.html.erb
 
    <div class="text-center bg-green-100 justify-center items-center  content-center block m-auto w-screen h-screen">
     
      <h1 class="text-center text-2xl bg-blue-200">
        Hi welcome to UltimateTicTac
      </h1>
      <p>I hope you don't mind but we've given you a username for this sessions from now on you will be known as </p>
      <p>If you would like to change it feel free to sign up, it comes with <em>added</em> benefits</p>
      <div>
        <p> would you like to  <%= link_to "sign up", new_player_registration_path, class: "text-blue-300 hover:text-blue-500" %>, <%= link_to "sign in", new_player_session_path, class: "text-blue-300 hover:text-blue-500" %> or join as a <%= link_to "guest", method: :post, class: "text-green-300 hover:text-blue-500" %>  for now? 
        </div>
        
          <div class= "my-6">
            <%= link_to "start match", new_gameroom_path, class: "py-2 px-4  bg-blue-700 hover:bg-blue-800 focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2 rounded-lg" %>   <%= link_to "Game rooms", gamerooms_path, class: "py-2 px-4  bg-blue-700 hover:bg-blue-800 focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2 rounded-lg " %>
          </div>
        
      </div>
    </div>
  